# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwrapper.proto\x12\nRPCDemoPkg\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"/\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"\x07\n\x05\x45mpty2y\n\x07Wrapper\x12\x37\n\nUploadPose\x12\x11.RPCDemoPkg.Empty\x1a\x14.RPCDemoPkg.Position\"\x00\x12\x35\n\x0bUploadImage\x12\x11.RPCDemoPkg.Empty\x1a\x11.RPCDemoPkg.Image\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=29
  _globals['_IMAGE']._serialized_end=50
  _globals['_POSITION']._serialized_start=52
  _globals['_POSITION']._serialized_end=99
  _globals['_EMPTY']._serialized_start=101
  _globals['_EMPTY']._serialized_end=108
  _globals['_WRAPPER']._serialized_start=110
  _globals['_WRAPPER']._serialized_end=231
# @@protoc_insertion_point(module_scope)
