# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wrapper_pb2 as wrapper__pb2


class WrapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPose = channel.unary_unary(
                '/RPCDemoPkg.Wrapper/UploadPose',
                request_serializer=wrapper__pb2.Empty.SerializeToString,
                response_deserializer=wrapper__pb2.Position.FromString,
                )
        self.UploadImage = channel.unary_unary(
                '/RPCDemoPkg.Wrapper/UploadImage',
                request_serializer=wrapper__pb2.Empty.SerializeToString,
                response_deserializer=wrapper__pb2.Image.FromString,
                )


class WrapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WrapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPose': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPose,
                    request_deserializer=wrapper__pb2.Empty.FromString,
                    response_serializer=wrapper__pb2.Position.SerializeToString,
            ),
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=wrapper__pb2.Empty.FromString,
                    response_serializer=wrapper__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RPCDemoPkg.Wrapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Wrapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RPCDemoPkg.Wrapper/UploadPose',
            wrapper__pb2.Empty.SerializeToString,
            wrapper__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RPCDemoPkg.Wrapper/UploadImage',
            wrapper__pb2.Empty.SerializeToString,
            wrapper__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
